### ISSUE TITLE
Error when a space character is a token

### ISSUE THREAD

**Issue by IHMCBrodie** [pyconll/pyconll#126]
**Describe the bug**
When parsing a sentence with spacy if there are two space characters right next to each other (i.e "#ONPC &nbsp;comment") it is possible that a space character can be a token and as such it's possible for CoNLL-U formatted data to have a space character as a token. When this is the case pyconll produces the following error:  
`pyconll.exception.ParseError: Error parsing "None" properly. Please check against CoNLL format spec.`

**To Reproduce**
This will a occur with a single line in a CoNLL-U formatted file where a space character is in the form and lemma column that looks like this:  
1&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;SPACE&nbsp;&nbsp;&nbsp;&nbsp;\_SP&nbsp;&nbsp;&nbsp;&nbsp;\_SP&nbsp;&nbsp;&nbsp;&nbsp;2&nbsp;&nbsp;&nbsp;&nbsp;\_&nbsp;&nbsp;&nbsp;&nbsp;\_&nbsp;&nbsp;&nbsp;&nbsp;\_  

Even though the 2nd and 3rd column look blank they have a space character there.

**Expected behavior**
Expected behavior is the space is maintained when reading in the CoNLL file and does not cause an error.

- OS: [e.g. Linux, Windows, MacOS] = MacOS
- Version [e.g. 2.2.1] = pyconll 3.1.0

**Comment by matgrioni** [comment]
Hi IHMCBrodie!

Just wanted to follow up on this (thanks for the great bug report btw :) ). You are correct in that the issue is the "_SP" value in the feats column. However, the issue is not that the value is non-standard, but rather that the [UD format](https://universaldependencies.org/format) expects the features to be attribute-value pairs. The quote is below

>All features should be represented as attribute-value pairs, with an equals sign (=) separating the attribute from the value.

In general, for cases like this it's a bit tricky and I still haven't thought entirely of how the application should handle output that is not strictly in the expected format. I think in either case, the library could stand to improve its diagnostics and error output quite a bit. A fair share of bugs relate to not being able to understand where an error in a conll file that is preventing parsing.

**Comment by IHMCBrodie** [comment]
Hey I appreciate you addressing this so quickly! Yeah sorry I should have been more clear when I said non-standard that was part of what I meant was the it was not an attribute-value pair. 

If I may suggest for this particular case that one way to handle it might be just to make the attribute and value from the value. For example, if it has "_SP" and you pick up that it's not in attribute-value format than you can turn it into "_SP=_SP" perhaps. I know this is not a great solution but would prevent the error and still allow the file to be read. Maybe a warning could be output when this occurs so the user is still made aware. Just some thoughts.

Although I am still not sure as to why the code that I was using ([here](https://github.com/Heidelberg-NLP/xsrl_mbert_aligner/blob/0637df7feeba67d6d6d90841f4415f89deefc66c/pre_process/text_to_CoNLL.py) if you're interested) decided to place "_SP" in the feats column and not in attribute-value format. I should investigate if it's a misstep on that repo's part (the one linked above) or if it's part of what spacy returns as a feat when parsing the sentence. If it's on spacy's part would probably be a good bug to submit and see if it's the behavior they expect or not.

**Comment by matgrioni** [comment]
I think having a non-strict mode would work best. The type of Token.feats is already Dict[str, Set[str]], so having an empty set on the feats is not a technical issue. It is only policy that it is checked, but a policy that can easily be done away with if the caller desires. I'll create another issue for creating this mode, and also for improving diagnostics.

I have found that external projects will tend to call a lot of things CoNLL and CoNLL-U so I'm not surprised they don't match the exact spec, although it's also well documented what it is for CoNLL-U at least.
