### ISSUE TITLE
Wrong encoding picked up by pyconll

### ISSUE THREAD

**Issue by ZmeiGorynych** [pyconll/pyconll#35]
When trying to import the UD datasets using load_from_file, I ran into issues because Python was assuming the wrong encoding    (cp-1252 rather than UTF-8). 
I worked around it by loading the file myself with the correct encoding, then using load_from_string.

This issue could be fixed by replacing in line 46 of load.py 
`with open(filename) as f:` by
```
import codecs
f = codecs.open(filename, encoding='utf-8')
```
Shall I submit a pull request for that?

**Comment by matgrioni** [comment]
Hi,

Thanks for bringing my attention to this. I should have specified the encoding when opening the file as UTF-8, but importing `codecs` shouldn't be necessary. `with open(filename, encoding='utf-8') as f` should work as well in Python 3.x. Feel free to submit a pull request if you'd like! I'd also be happy to make the change myself if you prefer.

- Matias

**Comment by matgrioni** [comment]
Out of curiosity, are you running this on a Windows machine? This might explain why I haven't seen this before, since python uses `locale.getpreferredencoding()` to determine which encoding to use when opening files, rather than always using a fixed encoding.

**Comment by ZmeiGorynych** [comment]
I'm running it both on Ubuntu and Windows 10 Pro, the issue manifested on Windows :)

**Comment by matgrioni** [comment]
This should now be taken care of! Version 1.1.3 is on pypi. Thanks for the help and for identifying the fix needed.

-Matias

**Comment by ZmeiGorynych** [comment]
Thanks for pushing it to pypi so quickly! ;)
