### ISSUE TITLE
Support for reading single sentence

### ISSUE THREAD

**Issue by RealNicolasBourbaki** [pyconll/pyconll#50]
There are cases when you have to read in huuuuuge conll files, like hundreds of GB of a file. In these cases, it would be unwise to read in all data at a time, since the we might apply operations on single sentence and read in all together could take way to much memory.

So it would be good to have a function that read in single sentence at a time, just like the build-in 'open' function, after read in and operated, the pointer move on to the next sentence and the previous one would be collected as garbage.

**Comment by matgrioni** [comment]
Hi NianhengWu,

There should already be something for this use case in pyconll! For all the `load_` functions in the pyconll namespace, like `load_from_file`, there is an `iter_` alternative that will do exactly as you said and load one sentence at a time.

For the network API this technically downloads the entire file first and then operates on the file, and I am looking if I can stream the data as it comes in, but this is the one exception. `iter_from_file` should handle your use case.

Here is the documentation for it: https://pyconll.readthedocs.io/en/stable/pyconll/load.html#pyconll.load.iter_from_file.

**Comment by RealNicolasBourbaki** [comment]
Ah, thank you very much!!
